import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, PackageCheck, RefreshCw, Route, Truck, Users } from 'lucide-react';
import { toast } from 'sonner';
import { fetchBranchOverview, type BranchOverview, type BranchRun } from '../../lib/branch-operations-api';

const KPI_META = [
  ['deliveries_today','Deliveries Today',CalendarDays],['tomorrow','Tomorrow',CalendarDays],['upcoming','Upcoming',Clock3],
  ['awaiting_planning','Awaiting Planning',Route],['scheduled','Scheduled',CalendarDays],['in_progress','In Progress',Truck],
  ['completed','Completed',CheckCircle2],['failed_partial','Failed / Partial',AlertTriangle],['incoming_stock','Incoming Stock',PackageCheck],
  ['open_exceptions','Open Exceptions',AlertTriangle],['available_branch_drivers','Available Branch Drivers',Users],
] as const;
const TABS = ['awaiting_planning','scheduled','in_progress','completed','exceptions'] as const;
const LABELS:Record<string,string>={awaiting_planning:'Awaiting Planning',scheduled:'Scheduled',in_progress:'In Progress',completed:'Completed',exceptions:'Exceptions'};

function RunCard({run}:{run:BranchRun}) {
  const method=run.transport_method || 'VEHICLE'; const handler=method==='VEHICLE' ? run.driver : run.handler;
  return <article className={`rounded-xl border bg-white p-4 shadow-sm ${run.delivery_date && run.readiness!=='READY' ? 'border-amber-300' : 'border-slate-200'}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-slate-900">{run.customer || run.run_number || 'Delivery run'}</p><p className="mt-1 text-sm text-slate-500">{run.area || 'Area not recorded'}</p></div><div className="flex flex-wrap gap-1"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">{method.replaceAll('_',' ')}</span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${run.readiness==='READY'?'bg-emerald-50 text-emerald-700':run.readiness==='PARTIALLY_PLANNED'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}`}>{run.readiness?.replaceAll('_',' ') || String(run.status).replaceAll('_',' ')}</span></div></div>
    {run.products?.length ? <p className="mt-2 line-clamp-2 text-xs text-slate-600">Products: {run.products.join(', ')}</p> : null}
    <dl className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600 sm:grid-cols-4"><div><dt className="text-slate-400">Agent</dt><dd>{run.field_agent || 'Unassigned'}</dd></div><div><dt className="text-slate-400">{method==='VEHICLE'?'Driver':'Handler'}</dt><dd>{handler || 'Unassigned'}</dd></div><div><dt className="text-slate-400">Vehicle / route</dt><dd>{method==='VEHICLE' ? run.vehicle || 'Unassigned' : run.run_number || 'Route needed'}</dd></div><div><dt className="text-slate-400">Planned</dt><dd>{run.delivery_date || 'Date needed'} {run.expected_time || ''}</dd></div></dl>
    {run.missing_requirements?.length ? <p className="mt-2 text-xs font-medium text-amber-700">Needs: {run.missing_requirements.join(', ')}</p> : null}
  </article>;
}

export default function BranchOperations({onNavigate}:{onNavigate:(page:string)=>void}) {
  const [data,setData]=useState<BranchOverview|null>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<typeof TABS[number]>('awaiting_planning'); const [upcoming,setUpcoming]=useState<'today'|'tomorrow'|'this_week'>('today');
  const boardRef=useRef<HTMLElement>(null); const upcomingRef=useRef<HTMLElement>(null);
  const load=async()=>{setLoading(true);try{setData(await fetchBranchOverview())}catch(error){toast.error(error instanceof Error?error.message:'Unable to load branch operations.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const openKpi=(key:string)=>{if(key==='incoming_stock')return onNavigate('stock-transfers');if(key==='available_branch_drivers')return onNavigate('branch-team');if(key==='deliveries_today'||key==='tomorrow'||key==='upcoming'){setUpcoming(key==='deliveries_today'?'today':key==='tomorrow'?'tomorrow':'this_week');upcomingRef.current?.scrollIntoView({behavior:'smooth'});return;}setTab(key==='failed_partial'||key==='open_exceptions'?'exceptions':key as typeof tab);boardRef.current?.scrollIntoView({behavior:'smooth'});};
  return <div className="space-y-6 p-4 sm:p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-900">Branch Operations</h1><p className="mt-1 text-sm text-slate-500">Deliveries, stock and team availability within your assigned branch scope.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>onNavigate('smart-living-deliveries')} className="min-h-11 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white">Open Delivery Planner</button><button onClick={()=>void load()} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 text-sm font-medium text-slate-700 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-6">{KPI_META.map(([key,label,Icon])=><button key={key} onClick={()=>openKpi(key)} className="min-w-0 rounded-xl border bg-white p-4 text-left shadow-sm transition hover:border-blue-300"><span className="inline-flex rounded-lg bg-blue-50 p-2 text-blue-600"><Icon className="h-5 w-5"/></span><strong className="mt-3 block text-2xl text-slate-900">{data?.kpis[key] ?? '—'}</strong><span className="text-xs text-slate-500 sm:text-sm">{label}</span></button>)}</section>
  <section className={`rounded-2xl border p-4 ${data?.tomorrow_summary.planning_required?'border-amber-300 bg-amber-50':'border-emerald-200 bg-emerald-50'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Tomorrow planning</h2><p className="text-sm text-slate-600">Total {data?.tomorrow_summary.total||0} · Ready {data?.tomorrow_summary.ready||0} · Planning Required {data?.tomorrow_summary.planning_required||0}</p></div>{data?.tomorrow_summary.planning_required ? <button onClick={()=>openKpi('tomorrow')} className="min-h-11 rounded-lg bg-amber-600 px-4 text-sm font-medium text-white">Review unplanned deliveries</button>:null}</div></section>
  <section ref={boardRef} className="scroll-mt-4 rounded-2xl border bg-slate-50 p-3 sm:p-5"><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{TABS.map(key=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium ${tab===key?'bg-blue-600 text-white':'bg-white text-slate-600'}`}>{LABELS[key]} <span className="ml-1 opacity-75">{data?.board[key].length||0}</span></button>)}</div><div className="grid gap-3 lg:grid-cols-2">{(data?.board[tab]||[]).map(run=><RunCard key={`${run.record_type}-${run.id}`} run={run}/>)}{!loading&&!data?.board[tab].length&&<p className="col-span-full rounded-xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">No deliveries in this stage.</p>}</div></section>
  <section ref={upcomingRef} className="scroll-mt-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-slate-900">Upcoming Deliveries</h2><div className="flex rounded-lg bg-slate-100 p-1">{(['today','tomorrow','this_week'] as const).map(key=><button key={key} onClick={()=>setUpcoming(key)} className={`rounded-md px-3 py-1.5 text-xs font-medium capitalize ${upcoming===key?'bg-white text-blue-700 shadow-sm':'text-slate-500'}`}>{key.replaceAll('_',' ')}</button>)}</div></div><div className="grid gap-3 lg:grid-cols-2">{(data?.upcoming[upcoming]||[]).map(run=><RunCard key={`${run.record_type}-${run.id}`} run={run}/>)}{!loading&&!data?.upcoming[upcoming].length&&<p className="rounded-xl border border-dashed p-6 text-sm text-slate-500">No upcoming deliveries for this period.</p>}</div></section></div>;
}
