import { useEffect, useState, type FormEvent } from 'react';
import { AlertTriangle, Bell, CalendarClock, Car, FileText, Fuel, Gauge, History, LogOut, Menu, Plus, Receipt, ShieldAlert, UserRound, Wrench, X } from 'lucide-react';
import { toast } from 'sonner';
import type { SessionUser } from '../../lib/auth-session';
import { ApiRequestError } from '../../lib/api';
import {
  createPersonalRecord, createPersonalVehicle, fetchPersonalDashboard, fetchPersonalExpenseSummary,
  fetchPersonalProfile, fetchPersonalRecords, fetchPersonalTimeline, fetchPersonalVehicles,
  renewPersonalDocument, updatePersonalProfile, updatePersonalRecord, updatePersonalVehicle,
  type PersonalVehicle,
} from '../../lib/personal-vehicle-api';

type Section = 'dashboard' | 'vehicles' | 'services' | 'faults' | 'accidents' | 'fuel' | 'expenses' | 'documents' | 'reminders' | 'timeline' | 'profile';
const sections: Array<{ id: Section; label: string; icon: any }> = [
  { id: 'dashboard', label: 'Dashboard', icon: Gauge }, { id: 'vehicles', label: 'My Vehicles', icon: Car },
  { id: 'services', label: 'Service History', icon: Wrench }, { id: 'faults', label: 'Faults & Repairs', icon: AlertTriangle },
  { id: 'accidents', label: 'Accidents', icon: ShieldAlert }, { id: 'fuel', label: 'Fuel / Charging', icon: Fuel },
  { id: 'expenses', label: 'Expenses', icon: Receipt }, { id: 'documents', label: 'Documents', icon: FileText },
  { id: 'reminders', label: 'Reminders', icon: CalendarClock }, { id: 'timeline', label: 'Vehicle Timeline', icon: History },
  { id: 'profile', label: 'Profile', icon: UserRound },
];
const vehicleTypes = ['motorcycle', 'tricycle', 'saloon_car', 'suv', 'pickup', 'van', 'other'];
const money = new Intl.NumberFormat('en-GH', { style: 'currency', currency: 'GHS' });
const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 8)}01`;

const recordFields: Record<string, Array<[string, string, string?]>> = {
  services: [['record_date', 'Service date', 'date'], ['mileage', 'Mileage', 'number'], ['service_type', 'Service type'], ['mechanic_or_garage', 'Mechanic / garage'], ['work_performed', 'Work performed'], ['labour_cost', 'Labour cost', 'number'], ['parts_cost', 'Parts cost', 'number'], ['other_cost', 'Other cost', 'number'], ['next_service_date', 'Next service date', 'date'], ['next_service_mileage', 'Next service mileage', 'number'], ['notes', 'Notes']],
  faults: [['record_date', 'Date noticed', 'date'], ['mileage', 'Mileage', 'number'], ['category', 'Category'], ['description', 'Description'], ['severity', 'Severity'], ['vehicle_usable', 'Vehicle usable: yes / no / unsure'], ['diagnosis', 'Diagnosis'], ['estimated_repair_cost', 'Estimated repair cost', 'number'], ['actual_repair_cost', 'Actual repair cost', 'number'], ['repair_date', 'Repair date', 'date'], ['resolution_notes', 'Resolution notes']],
  accidents: [['record_date', 'Record date', 'date'], ['incident_at', 'Accident date / time', 'datetime-local'], ['mileage', 'Mileage', 'number'], ['location', 'Location'], ['description', 'Description'], ['damage_areas', 'Damage areas (comma separated)'], ['severity', 'Severity'], ['vehicle_drivable', 'Vehicle drivable: yes / no'], ['police_report_reference', 'Police report reference'], ['insurance_claim_reference', 'Insurance claim reference'], ['repair_estimate', 'Repair estimate', 'number'], ['repair_cost', 'Repair cost', 'number'], ['repair_status', 'Repair status'], ['completion_date', 'Completion date', 'date'], ['notes', 'Notes']],
  fuel: [['record_date', 'Date', 'date'], ['mileage', 'Mileage', 'number'], ['fuel_type', 'Fuel / energy type'], ['quantity', 'Fuel quantity', 'number'], ['total_cost', 'Fuel cost', 'number'], ['energy_used', 'Energy used (EV)', 'number'], ['charging_cost', 'Charging cost (EV)', 'number'], ['station', 'Station'], ['charging_location', 'Charging location'], ['tank_level', 'Full / partial'], ['battery_before', 'Battery before %', 'number'], ['battery_after', 'Battery after %', 'number']],
  expenses: [['record_date', 'Date', 'date'], ['category', 'Category'], ['title', 'Description'], ['amount', 'Amount', 'number'], ['notes', 'Notes']],
  documents: [['record_date', 'Record date', 'date'], ['document_type', 'Document type'], ['document_number', 'Document number'], ['issue_date', 'Issue date', 'date'], ['expiry_date', 'Expiry date', 'date'], ['provider', 'Provider'], ['notes', 'Notes']],
  reminders: [['record_date', 'Created date', 'date'], ['reminder_type', 'Reminder type'], ['title', 'Reminder title'], ['due_date', 'Due date', 'date'], ['due_mileage', 'Due mileage', 'number'], ['notes', 'Notes']],
};

export default function PersonalVehiclePortal({ currentUser, onLogout }: { currentUser: SessionUser; onLogout: () => void }) {
  const initial = window.location.pathname.split('/').filter(Boolean).at(-1) as Section;
  const [section, setSection] = useState<Section>(sections.some((item) => item.id === initial) ? initial : 'dashboard');
  const [mobileOpen, setMobileOpen] = useState(false); const [vehicles, setVehicles] = useState<PersonalVehicle[]>([]);
  const [selectedVehicle, setSelectedVehicle] = useState(''); const [dashboard, setDashboard] = useState<any>(null);
  const [records, setRecords] = useState<any[]>([]); const [pagination, setPagination] = useState<any>(null);
  const [expenseSummary, setExpenseSummary] = useState<any>(null); const [profile, setProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState<'vehicle' | 'record' | null>(null);
  const [page, setPage] = useState(1); const [filters, setFilters] = useState({ start_date: monthStart, end_date: today });

  const navigate = (next: Section) => { setSection(next); setPage(1); setMobileOpen(false); window.history.pushState({ personalSection: next }, '', `/my-vehicles/${next}`); };
  useEffect(() => { window.history.replaceState({ personalSection: section }, '', `/my-vehicles/${section}`); const pop = () => { const next = window.location.pathname.split('/').filter(Boolean).at(-1) as Section; if (sections.some((item) => item.id === next)) setSection(next); }; window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop); }, []);

  const load = async () => {
    setLoading(true); setError('');
    try {
      const vehicleRows = await fetchPersonalVehicles(); setVehicles(vehicleRows);
      const common = { vehicle_id: selectedVehicle, ...filters };
      if (section === 'dashboard') setDashboard(await fetchPersonalDashboard(common));
      else if (section === 'vehicles') setRecords(vehicleRows);
      else if (section === 'timeline') { const data = await fetchPersonalTimeline({ vehicle_id: selectedVehicle, page, page_size: 20 }); setRecords(data.events); setPagination(data.pagination); }
      else if (section === 'profile') setProfile(await fetchPersonalProfile());
      else { const data = await fetchPersonalRecords(section, { vehicle_id: selectedVehicle, page, page_size: 20, ...filters }); setRecords(data.records); setPagination(data.pagination); if (section === 'expenses') setExpenseSummary(await fetchPersonalExpenseSummary(common)); }
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Personal vehicle data could not be loaded.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [section, selectedVehicle, page]);

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white px-4 md:pl-72"><button onClick={() => setMobileOpen(true)} className="rounded p-2 md:hidden"><Menu /></button><div><b>Flux My Vehicles</b><span className="ml-2 hidden text-sm text-slate-500 sm:inline">Personal vehicle care</span></div><div className="flex items-center gap-3"><Bell className="h-5 w-5" /><span className="hidden text-sm sm:inline">{currentUser.full_name}</span><button onClick={onLogout} title="Logout"><LogOut className="h-5 w-5" /></button></div></header>
    <aside className={`fixed inset-y-0 left-0 z-40 w-64 bg-slate-950 p-4 text-white transition-transform md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-6 flex items-center justify-between"><div><b className="text-lg">MY VEHICLES</b><p className="text-xs text-slate-400">Ownership & care</p></div><button onClick={() => setMobileOpen(false)} className="md:hidden"><X /></button></div><nav className="space-y-1">{sections.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => navigate(id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${section === id ? 'bg-blue-600' : 'text-slate-300 hover:bg-slate-800'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav><button onClick={onLogout} className="mt-6 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-slate-300 hover:bg-slate-800"><LogOut className="h-4 w-4" />Logout</button></aside>
    {mobileOpen && <button className="fixed inset-0 z-30 bg-black/40 md:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="p-4 md:ml-64 md:p-7"><div className="mx-auto max-w-7xl space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">{sections.find((item) => item.id === section)?.label}</h1><p className="text-sm text-slate-500">Private records for your personal vehicles only.</p></div>{!['profile', 'timeline', 'dashboard'].includes(section) && <button onClick={() => setModal(section === 'vehicles' ? 'vehicle' : 'record')} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Add {section === 'vehicles' ? 'vehicle' : 'record'}</button>}</div>
      {!['profile'].includes(section) && <div className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><select value={selectedVehicle} onChange={(e) => setSelectedVehicle(e.target.value)} className="min-w-0 rounded-lg border px-3 py-2"><option value="">All vehicles</option>{vehicles.map((item) => <option key={item.id} value={item.id}>{item.registration_number} · {label(item.vehicle_type)}</option>)}</select><input aria-label="From date" type="date" value={filters.start_date} onChange={(e) => setFilters({ ...filters, start_date: e.target.value })} className="min-w-0 rounded-lg border px-3 py-2" /><input aria-label="To date" type="date" value={filters.end_date} onChange={(e) => setFilters({ ...filters, end_date: e.target.value })} className="min-w-0 rounded-lg border px-3 py-2" /><button onClick={() => void load()} className="rounded-lg border px-3 py-2">Apply filters</button></div>}
      {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      {loading ? <div className="py-20 text-center text-slate-500">Loading vehicle records…</div> : section === 'dashboard' ? <Dashboard data={dashboard} /> : section === 'vehicles' ? <VehicleList vehicles={vehicles} onChanged={load} /> : section === 'profile' ? <Profile profile={profile} onChanged={load} /> : <RecordList section={section} records={records} expenseSummary={expenseSummary} onChanged={load} />}
      {pagination?.pages > 1 && <div className="flex justify-center gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-2 disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm">{page} / {pagination.pages}</span><button disabled={page >= pagination.pages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-2 disabled:opacity-40">Next</button></div>}
    </div></main>
    {modal === 'vehicle' && <VehicleForm onClose={() => setModal(null)} onSaved={async () => { setModal(null); await load(); }} />}
    {modal === 'record' && <RecordForm section={section} vehicles={vehicles} selectedVehicle={selectedVehicle} onClose={() => setModal(null)} onSaved={async () => { setModal(null); await load(); }} />}
  </div>;
}

function Dashboard({ data }: { data: any }) {
  if (!data) return <Empty text="No dashboard data yet." />;
  const s = data.summary || {}; const cards = [['Total vehicles', s.total_vehicles], ['Active', s.active_vehicles], ['Current mileage', s.current_mileage], ['Open faults', s.open_faults], ['Accident repairs', s.unresolved_accident_repairs], ['Document expiries', s.document_expiries], ['Reminders', s.reminders], ['Fuel this month', money.format(s.monthly_fuel_cost || 0)], ['Ownership cost', money.format(s.monthly_ownership_cost || 0)]];
  return <><div className="grid grid-cols-2 gap-3 min-[430px]:grid-cols-3 lg:grid-cols-5">{cards.map(([labelText, value]) => <div key={String(labelText)} className="min-w-0 rounded-xl border bg-white p-3 sm:p-4"><p className="truncate text-xs text-slate-500">{labelText}</p><p className="mt-1 truncate text-lg font-bold sm:text-xl">{value}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Vehicle health">{data.vehicles?.length ? data.vehicles.map((item: any) => <div key={item.id} className="mb-2 rounded-lg bg-slate-50 p-3"><div className="flex justify-between gap-2"><b>{item.registration_number}</b><span className="capitalize">{item.health?.band} · {item.health?.score}/100</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><Info name="Last service" value={item.last_service?.record_date || 'None'} /><Info name="Next service" value={item.next_service?.due_date || item.next_service?.due_mileage || 'Not set'} /></div><p className="mt-2 text-xs text-slate-500">{item.health?.disclaimer}</p>{item.health?.warnings?.map((warning: any) => <p key={warning.code} className="mt-1 text-sm text-amber-700">{warning.message}</p>)}</div>) : <Empty text="Add your first vehicle to calculate health." />}</Panel><Panel title="Recent activity"><Rows rows={data.recent_activity || []} /></Panel></div></>;
}

function VehicleList({ vehicles, onChanged }: { vehicles: PersonalVehicle[]; onChanged: () => Promise<void> }) {
  if (!vehicles.length) return <Empty text="No personal vehicles added yet." />;
  const change = async (id: string, status: string) => { if (!confirm(`Mark this vehicle as ${status}?`)) return; try { await updatePersonalVehicle(id, { status, change_reason: `Owner marked vehicle ${status}.` }); await onChanged(); } catch (error) { toast.error(message(error)); } };
  const edit = async (item: PersonalVehicle) => { const mileage = prompt('Current mileage', String(item.current_mileage || 0)); if (mileage === null) return; const numeric = Number(mileage); if (!Number.isFinite(numeric) || numeric < 0) return toast.error('Enter a valid mileage.'); const payload: Record<string, unknown> = { current_mileage: numeric, change_reason: 'Owner updated vehicle mileage.' }; if (numeric < Number(item.current_mileage || 0)) { const reason = prompt('Mileage is lower. Enter the correction reason for the audit trail.'); if (!reason) return; payload.correction_reason = reason; } try { await updatePersonalVehicle(item.id, payload); await onChanged(); } catch (error) { toast.error(message(error)); } };
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{vehicles.map((item) => <article key={item.id} className="min-w-0 rounded-xl border bg-white p-5"><div className="flex justify-between gap-2"><div className="min-w-0"><h2 className="truncate text-lg font-bold">{item.registration_number}</h2><p className="truncate text-sm text-slate-500">{item.make} {item.model} · {label(item.vehicle_type)}</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{item.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info name="Mileage" value={item.current_mileage || 0} /><Info name="Fuel / energy" value={item.fuel_type} /><Info name="Year" value={item.year} /><Info name="Transmission" value={item.transmission || '—'} /></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void edit(item)} className="rounded border px-3 py-1.5 text-sm">Update mileage</button><button onClick={() => void change(item.id, 'sold')} className="rounded border px-3 py-1.5 text-sm">Mark sold</button><button onClick={() => void change(item.id, 'archived')} className="rounded border px-3 py-1.5 text-sm">Archive</button></div></article>)}</div>;
}

function RecordList({ section, records, expenseSummary, onChanged }: { section: Section; records: any[]; expenseSummary: any; onChanged: () => Promise<void> }) {
  const complete = async (item: any) => { try { await updatePersonalRecord(section, item.id, { status: section === 'faults' ? 'resolved' : 'completed', status_note: 'Completed by vehicle owner.' }); await onChanged(); } catch (error) { toast.error(message(error)); } };
  const renew = async (item: any) => { const expiry = prompt('New expiry date (YYYY-MM-DD)'); if (!expiry) return; try { await renewPersonalDocument(item.id, { issue_date: today, expiry_date: expiry, document_number: item.document_number, provider: item.provider }); await onChanged(); } catch (error) { toast.error(message(error)); } };
  return <>{section === 'expenses' && expenseSummary && <Panel title="Ownership cost summary"><div className="flex flex-wrap gap-3">{Object.entries(expenseSummary.by_category || {}).map(([key, value]) => <span key={key} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm capitalize">{label(key)}: {money.format(Number(value))}</span>)}<b className="px-3 py-1.5">Total: {money.format(expenseSummary.total || 0)}</b></div></Panel>}{!records.length ? <Empty text={`No ${section.replaceAll('_', ' ')} records yet.`} /> : <div className="space-y-3">{records.map((item) => <article key={item.id || item.key} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-semibold">{item.title || item.description || item.document_type || item.registration_number || label(item.event_type || section)}</h2><p className="text-xs text-slate-500">{localDate(item.incident_at || item.record_date || item.occurred_at || item.created_at)}</p></div>{item.status && <span className="rounded-full bg-slate-100 px-2 py-1 text-xs capitalize">{label(item.status)}</span>}</div><div className="mt-3 grid gap-x-5 gap-y-1 text-sm sm:grid-cols-2">{Object.entries(item).filter(([key, value]) => !['id', 'key', 'personal_owner_user_id', 'vehicle_id', 'created_by', 'status_history', 'attachments', 'created_at', 'updated_at', 'notes', 'record_scope'].includes(key) && value !== null && typeof value !== 'object').slice(0, 10).map(([key, value]) => <Info key={key} name={label(key)} value={key.includes('cost') || key === 'amount' ? money.format(Number(value)) : String(value)} />)}</div>{item.notes && <p className="mt-3 text-sm text-slate-600">{item.notes}</p>}<div className="mt-3 flex gap-2">{['faults', 'accidents', 'reminders'].includes(section) && !['resolved', 'completed', 'dismissed'].includes(item.status) && <button onClick={() => void complete(item)} className="rounded border px-3 py-1.5 text-sm">Mark complete</button>}{section === 'documents' && item.status !== 'renewed' && <button onClick={() => void renew(item)} className="rounded border px-3 py-1.5 text-sm">Renew</button>}</div></article>)}</div>}</>;
}

function VehicleForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState<any>({ vehicle_type: 'saloon_car', registration_number: '', make: '', model: '', year: '', color: '', fuel_type: 'petrol', transmission: 'automatic', current_mileage: '', chassis_number: '', engine_number: '', purchase_date: '', purchase_mileage: '', tyre_size: '', engine_capacity: '', vehicle_photo: '', notes: '' }); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await createPersonalVehicle(form); toast.success('Personal vehicle added.'); await onSaved(); } catch (error) { toast.error(message(error)); } finally { setBusy(false); } };
  return <Modal title="Add personal vehicle" onClose={onClose}><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><SelectField name="vehicle_type" labelText="Vehicle type" value={form.vehicle_type} options={vehicleTypes} setForm={setForm} /><FormField name="registration_number" labelText="Registration number" form={form} setForm={setForm} required /><FormField name="make" labelText="Make" form={form} setForm={setForm} required /><FormField name="model" labelText="Model" form={form} setForm={setForm} required /><FormField name="year" labelText="Year" type="number" form={form} setForm={setForm} required /><FormField name="color" labelText="Colour" form={form} setForm={setForm} /><SelectField name="fuel_type" labelText="Fuel / energy" value={form.fuel_type} options={['petrol', 'diesel', 'lpg', 'electric', 'hybrid', 'other']} setForm={setForm} /><SelectField name="transmission" labelText="Transmission" value={form.transmission} options={['automatic', 'manual', 'other']} setForm={setForm} /><FormField name="current_mileage" labelText="Current mileage" type="number" form={form} setForm={setForm} /><FormField name="chassis_number" labelText="Chassis number" form={form} setForm={setForm} /><FormField name="engine_number" labelText="Engine number" form={form} setForm={setForm} /><FormField name="purchase_date" labelText="Purchase date" type="date" form={form} setForm={setForm} /><FormField name="purchase_mileage" labelText="Purchase mileage" type="number" form={form} setForm={setForm} /><FormField name="tyre_size" labelText="Tyre size" form={form} setForm={setForm} />{['motorcycle', 'tricycle', 'other'].includes(form.vehicle_type) && <FormField name="engine_capacity" labelText="Engine capacity" form={form} setForm={setForm} />}<FormField name="vehicle_photo" labelText="Vehicle photo URL" type="url" form={form} setForm={setForm} /><FormField name="notes" labelText="Notes" form={form} setForm={setForm} /><Actions busy={busy} onClose={onClose} /></form></Modal>;
}

function RecordForm({ section, vehicles, selectedVehicle, onClose, onSaved }: { section: Section; vehicles: PersonalVehicle[]; selectedVehicle: string; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState<any>({ vehicle_id: selectedVehicle || vehicles[0]?.id || '', record_date: today, incident_at: `${today}T12:00`, severity: 'medium', status: section === 'services' ? 'completed' : undefined }); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const payload = { ...form, damage_areas: typeof form.damage_areas === 'string' ? form.damage_areas.split(',').map((x: string) => x.trim()).filter(Boolean) : form.damage_areas, vehicle_drivable: form.vehicle_drivable === 'yes' ? true : form.vehicle_drivable === 'no' ? false : undefined }; await createPersonalRecord(section, payload); toast.success('Vehicle record saved.'); await onSaved(); } catch (error) { toast.error(message(error)); } finally { setBusy(false); } };
  return <Modal title={`Add ${section.replaceAll('_', ' ')}`} onClose={onClose}><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Vehicle<select required value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2.5"><option value="">Select vehicle</option>{vehicles.map((item) => <option key={item.id} value={item.id}>{item.registration_number}</option>)}</select></label>{(recordFields[section] || []).map(([name, labelText, type]) => <FormField key={name} name={name} labelText={labelText} type={type} form={form} setForm={setForm} required={['record_date', 'service_type', 'work_performed', 'category', 'description', 'incident_at', 'location', 'title', 'amount', 'document_type', 'reminder_type'].includes(name)} />)}<Actions busy={busy} onClose={onClose} /></form></Modal>;
}

function Profile({ profile, onChanged }: { profile: any; onChanged: () => Promise<void> }) { const [form, setForm] = useState({ full_name: profile?.full_name || '', phone: profile?.phone || '' }); const save = async (e: FormEvent) => { e.preventDefault(); try { await updatePersonalProfile(form); toast.success('Profile updated.'); await onChanged(); } catch (error) { toast.error(message(error)); } }; return <Panel title="Personal account"><form onSubmit={save} className="max-w-xl space-y-3"><FormField name="full_name" labelText="Full name" form={form} setForm={setForm} required /><FormField name="phone" labelText="Phone" form={form} setForm={setForm} required /><p className="text-sm text-slate-500">{profile?.email}</p><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Save profile</button></form></Panel>; }
function Modal({ title, onClose, children }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-5"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose}><X /></button></div>{children}</div></div>; }
function FormField({ name, labelText, type = 'text', form, setForm, required = false }: any) { return <label className="text-sm">{labelText}<input type={type} required={required} min={type === 'number' ? 0 : undefined} value={form[name] ?? ''} onChange={(e) => setForm((current: any) => ({ ...current, [name]: e.target.value }))} className="mt-1 w-full rounded-lg border px-3 py-2.5" /></label>; }
function SelectField({ name, labelText, value, options, setForm }: any) { return <label className="text-sm">{labelText}<select value={value} onChange={(e) => setForm((current: any) => ({ ...current, [name]: e.target.value }))} className="mt-1 w-full rounded-lg border px-3 py-2.5">{options.map((item: string) => <option key={item} value={item}>{label(item)}</option>)}</select></label>; }
function Actions({ busy, onClose }: any) { return <div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2 text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save'}</button></div>; }
function Panel({ title, children }: any) { return <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed bg-white p-12 text-center text-slate-500">{text}</div>; }
function Rows({ rows }: { rows: any[] }) { return rows.length ? <div className="space-y-2">{rows.map((item) => <div key={item.key || item.id} className="rounded-lg bg-slate-50 p-3"><b className="text-sm">{item.title}</b><p className="text-xs text-slate-500">{localDate(item.occurred_at)}</p></div>)}</div> : <Empty text="No recent activity." />; }
function Info({ name, value }: { name: string; value: any }) { return <div className="flex justify-between gap-2"><span className="text-slate-500">{name}</span><span className="text-right font-medium">{value ?? '—'}</span></div>; }
function label(value: string) { return String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (x) => x.toUpperCase()); }
function localDate(value: any) { if (!value) return '—'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleString(); }
function message(error: unknown) { return error instanceof ApiRequestError || error instanceof Error ? error.message : 'The action could not be completed.'; }
