import { useEffect, useState } from 'react';
import { Loader2, Save } from 'lucide-react';
import { toast } from 'sonner';
import { apiRequest } from '../../lib/api';

type Setting = { id: string; setting_type: string; value?: number | null; configuration?: Record<string, unknown> | null; effective_from?: string | null; effective_to?: string | null; reason?: string | null; changed_by_name?: string | null; changed_at?: string | null };
const labels: Record<string,string> = { maintenance_reserve_rate: 'Maintenance Reserve (%)', fuel_price_per_litre: 'Fuel Price Per Litre', vehicle_capital_profit_rule: 'Vehicle Capital / Profit Rule' };

export default function DispatchFinanceRateSettings({ isOwner }: { isOwner: boolean }) {
  const [settings, setSettings] = useState<Setting[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ setting_type: 'maintenance_reserve_rate', value: '25', mode: 'amount', effective_from: new Date().toISOString().slice(0,10), effective_to: '', reason: '' });
  const load = async () => { setLoading(true); try { const response = await apiRequest<{data:{settings:Setting[]}}>('/dispatch-financials/settings'); setSettings(response.data.settings || []); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load finance rates.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await apiRequest(`/dispatch-financials/settings/${form.setting_type}`, { method:'POST', body:JSON.stringify({ value:form.setting_type==='vehicle_capital_profit_rule'?undefined:Number(form.value), configuration:form.setting_type==='vehicle_capital_profit_rule'?{mode:form.mode,value:Number(form.value)}:undefined, effective_from:form.effective_from, effective_to:form.effective_to||undefined, reason:form.reason }) }); toast.success('Effective-dated finance setting saved.'); setForm((current)=>({...current,reason:''})); await load(); } catch(error) { toast.error(error instanceof Error?error.message:'Unable to save finance setting.'); } finally { setSaving(false); } };
  return <div className="space-y-5 rounded-2xl border border-gray-200 bg-white p-5"><div><h2 className="text-lg font-semibold text-slate-900">Dispatch Finance Rates</h2><p className="mt-1 text-sm text-slate-500">Changes apply by effective date. Approved dispatch snapshots retain the rate originally used.</p></div>
    {isOwner && <form onSubmit={submit} className="grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-3"><label className="text-xs">Setting<select className="mt-1 w-full rounded-lg border p-2.5" value={form.setting_type} onChange={(e)=>setForm({...form,setting_type:e.target.value})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{form.setting_type==='vehicle_capital_profit_rule'&&<label className="text-xs">Rule Mode<select className="mt-1 w-full rounded-lg border p-2.5" value={form.mode} onChange={(e)=>setForm({...form,mode:e.target.value})}><option value="amount">Fixed Amount</option><option value="percentage">Percentage</option></select></label>}<label className="text-xs">Value<input required min="0" step="0.01" type="number" className="mt-1 w-full rounded-lg border p-2.5" value={form.value} onChange={(e)=>setForm({...form,value:e.target.value})}/></label><label className="text-xs">Effective From<input required type="date" className="mt-1 w-full rounded-lg border p-2.5" value={form.effective_from} onChange={(e)=>setForm({...form,effective_from:e.target.value})}/></label><label className="text-xs">Effective To (optional)<input type="date" className="mt-1 w-full rounded-lg border p-2.5" value={form.effective_to} onChange={(e)=>setForm({...form,effective_to:e.target.value})}/></label><label className="text-xs md:col-span-2">Reason<input required className="mt-1 w-full rounded-lg border p-2.5" value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})}/></label><button disabled={saving} className="inline-flex items-center justify-center gap-2 self-end rounded-lg bg-blue-600 px-4 py-2.5 text-sm text-white disabled:opacity-60">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Schedule Rate</button></form>}
    {loading?<div className="flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin"/>Loading history…</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="p-2">Setting</th><th className="p-2">Value</th><th className="p-2">Effective Period</th><th className="p-2">Reason</th><th className="p-2">Changed By</th></tr></thead><tbody>{settings.map((item)=><tr key={item.id} className="border-b"><td className="p-2">{labels[item.setting_type]||item.setting_type}</td><td className="p-2">{item.value ?? `${item.configuration?.mode || ''} ${item.configuration?.value || ''}`}</td><td className="p-2">{item.effective_from||'Default'} – {item.effective_to||'Open'}</td><td className="p-2">{item.reason||'—'}</td><td className="p-2">{item.changed_by_name||'System'}</td></tr>)}</tbody></table>{!settings.length&&<div className="py-6 text-center text-sm text-slate-500">The 25% maintenance reserve default is active. Add a dated setting to change it.</div>}</div>}
  </div>;
}
