import { useEffect, useState } from 'react';
import { Loader2, RefreshCcw } from 'lucide-react';
import { toast } from 'sonner';
import { fetchDispatchFinanceAnalytics } from '../../lib/dispatch-financial-api';

const money=(value:unknown)=>`GHS ${Number(value||0).toLocaleString()}`;
type Option={id:string;name:string}; type Props={options?:{drivers?:Option[];vehicles?:Option[];branches?:Option[];funding_sources?:Option[]}};
export default function DispatchFinanceAnalytics({options}:Props){
  const [preset,setPreset]=useState('this_month'); const [pricing,setPricing]=useState(''); const [driver,setDriver]=useState(''); const [vehicle,setVehicle]=useState(''); const [branch,setBranch]=useState(''); const [funding,setFunding]=useState(''); const [loading,setLoading]=useState(true); const [data,setData]=useState<any>(null);
  const load=async()=>{setLoading(true);try{setData(await fetchDispatchFinanceAnalytics({preset,pricing_type:pricing||undefined,driver_id:driver||undefined,vehicle_id:vehicle||undefined,branch_id:branch||undefined,funding_source_id:funding||undefined}));}catch(error){toast.error(error instanceof Error?error.message:'Unable to load dispatch analytics.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[preset,pricing,driver,vehicle,branch,funding]); const s=data?.summary||{};
  return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Dispatch Finance Analytics</h2><p className="text-xs text-slate-500">Derived from approved dispatch snapshots and linked collection transactions.</p></div><div className="flex flex-wrap gap-2"><select className="rounded-lg border p-2 text-sm" value={preset} onChange={(e)=>setPreset(e.target.value)}><option value="today">Today</option><option value="this_week">This Week</option><option value="last_week">Last Week</option><option value="this_month">This Month</option></select><Select label="All Drivers" value={driver} setValue={setDriver} options={options?.drivers}/><Select label="All Vehicles" value={vehicle} setValue={setVehicle} options={options?.vehicles}/><Select label="All Branches" value={branch} setValue={setBranch} options={options?.branches}/><Select label="All Funding" value={funding} setValue={setFunding} options={options?.funding_sources}/><select className="rounded-lg border p-2 text-sm" value={pricing} onChange={(e)=>setPricing(e.target.value)}><option value="">All Pricing</option><option value="standard">Standard</option><option value="subsidized">Subsidized</option><option value="complimentary">Complimentary</option></select><button onClick={()=>void load()} className="rounded-lg border p-2">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCcw className="h-4 w-4"/>}</button></div></div>
    <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6">{[['Dispatches',s.dispatch_count||0],['Commercial Value',money(s.commercial_value)],['Customer Revenue',money(s.customer_revenue)],['Concessions',money(s.concessions)],['Fuel',money(s.fuel)],['Driver Compensation',money(s.driver_compensation)],['Maintenance Reserve',money(s.maintenance_reserve)],['Company Contribution',money(s.company_contribution)],['Collections',money(s.collections)],['Submissions',money(s.submissions)],['Outstanding',money(s.outstanding_reconciliation)]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-slate-50 p-3"><div className="text-[11px] text-slate-500">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>)}</div>
    {data?.records?.length?<details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-blue-700">Drill down ({data.records.length})</summary><div className="mt-2 overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left"><th className="p-2">Vehicle</th><th className="p-2">Pricing</th><th className="p-2">Commercial</th><th className="p-2">Customer</th><th className="p-2">Distance</th><th className="p-2">Driver Compensation</th></tr></thead><tbody>{data.records.map((row:any)=><tr key={row.dispatch_job_id} className="border-b"><td className="p-2">{row.vehicle_registration||'Unassigned'}</td><td className="p-2 capitalize">{row.pricing_type}</td><td className="p-2">{money(row.commercial_value)}</td><td className="p-2">{money(row.customer_charge)}</td><td className="p-2">{row.operational_distance_km||0} km</td><td className="p-2">{money(row.driver_compensation)}</td></tr>)}</tbody></table></div></details>:null}
  </div>;
}
function Select({label,value,setValue,options=[]}:{label:string;value:string;setValue:(value:string)=>void;options?:Option[]}){return <select className="rounded-lg border p-2 text-sm" value={value} onChange={(e)=>setValue(e.target.value)}><option value="">{label}</option>{options.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}
